<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.openmarkov</groupId>
  <artifactId>org.openmarkov.full</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>org.openmarkov.full</name>
  <description>Full Distribution of OpenMarkov</description>
  
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.core.gui</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.algorithm.hillclimbing</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.algorithm.pc</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
 
        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.gui</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.io</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.metric.aic</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
 
        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.metric.bayesian</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
 
        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.metric.bd</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
 
        <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.metric.entropy</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

         <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.metric.k2</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

         <dependency>
            <groupId>org.openmarkov</groupId>
            <artifactId>org.openmarkov.learning.metric.mdlm</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.16</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.10</version>
        </dependency>

        <dependency>
            <groupId>jdom</groupId>
            <artifactId>jdom</artifactId>
            <version>1.1</version>
        </dependency>
    </dependencies>

     <repositories>
        <repository>
            <id>release</id>
            <name>OpenMarkov</name>
            <url>http://openmarkov.org:8081/nexus/content/repositories/releases</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>snapshots</id>
            <name>OpenMarkov Snapshots</name>
            <url>http://openmarkov.org:8081/nexus/content/repositories/snapshots/</url>
            <layout>default</layout>
        </repository>
    </repositories>
    <distributionManagement>
        <repository>
            <uniqueVersion>false</uniqueVersion>
            <id>releases</id>
            <name>Releases</name>
            <url>http://openmarkov.org:8081/nexus/content/repositories/releases</url>
        </repository>
        <snapshotRepository>
            <uniqueVersion>true</uniqueVersion>
            <id>snapshots</id>
            <name>Snapshots</name>
            <url>http://openmarkov.org:8081/nexus/content/repositories/snapshots/</url>
        </snapshotRepository>
    </distributionManagement>     
</project>